set nocompatible

"----------------------------------------------------------------------------------------------------------------------"
" VIM-PLUG (Plugin-manager) section
"    (keep this at the top)
"----------------------------------------------------------------------------------------------------------------------"
" Specify a directory for plugins
" - For Neovim: stdpath('data') . '/plugged'
" - Avoid using standard Vim directory names like 'plugin'
call plug#begin('~/.vim/plugged')

" Make sure you use single quotes

" Shorthand notation; fetches https://github.com/junegunn/vim-easy-align
"Plug 'junegunn/vim-easy-align'
Plug 'junegunn/seoul256.vim'

" Plug 'w0rp/ale'
Plug 'christoomey/vim-tmux-navigator'
Plug 'majutsushi/tagbar'
Plug 'chrisbra/Colorizer'
if !has('nvim')
    Plug 'nvim-lualine/lualine.nvim'
endif
Plug 'tpope/vim-fugitive'
" Plug 'preservim/nerdtree'
" Plug 'mcchrish/nnn.vim'
Plug 'junegunn/fzf'
Plug 'junegunn/fzf.vim'
" Plug 'weynhamz/vim-plugin-minibufexpl'
Plug 'airblade/vim-rooter'
" Plug 'airblade/vim-gitgutter'  " REMOVED — replaced by gitsigns.nvim (lua)
Plug 'chrisbra/csv.vim'

Plug 'rust-lang/rust.vim'
" Plug 'ludovicchabant/vim-gutentags'  " REMOVED — LSP handles navigation; ctags was indexing entire monolith on exit
" Plug 'Yilin-Yang/vim-markbar'
Plug 'skywind3000/vim-quickui' 

" vim-only: Comment.nvim (lazy.nvim) provides gcc/gc in neovim
if !has('nvim')
    Plug 'tpope/vim-commentary'
endif
Plug 'tpope/vim-obsession'
Plug 'nanotee/zoxide.vim'

Plug 'wincent/ferret'
let g:FerretMap = 0
Plug 'stefandtw/quickfix-reflector.vim'

Plug 'dyng/ctrlsf.vim'
Plug 'vim-scripts/BufOnly.vim'

Plug 'ryanoasis/vim-devicons'


"
" Any valid git URL is allowed
"Plug 'https://github.com/junegunn/vim-github-dashboard.git'

" Multiple Plug commands can be written in a single line using | separators
"Plug 'SirVer/ultisnips' | Plug 'honza/vim-snippets'

" On-demand loading
"Plug 'scrooloose/nerdtree', { 'on':  'NERDTreeToggle' }
"Plug 'tpope/vim-fireplace', { 'for': 'clojure' }

" Using a non-master branch
"Plug 'rdnetto/YCM-Generator', { 'branch': 'stable' }

" Using a tagged release; wildcard allowed (requires git 1.9.2 or above)
"Plug 'fatih/vim-go', { 'tag': '*' }

" Plugin options
"Plug 'nsf/gocode', { 'tag': 'v.20150303', 'rtp': 'vim' }

" Plugin outside ~/.vim/plugged with post-update hook
"Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }

" Unmanaged plugin (manually installed and updated)
"Plug '~/my-prototype-plugin'

" Initialize plugin system
call plug#end()


"----------------------------------------------------------------------------------------------------------------------"
" Global Settings
"----------------------------------------------------------------------------------------------------------------------"
" Disable syntax highlighting of code inside Python docstrings (>>> doctests).
" This is a vim legacy syntax setting (python.vim), active alongside treesitter.
let g:python_no_doctest_code_highlight = 1

" make backspace work as expected
  set backspace=indent,eol,start

" [global] set nowrap        do not wrap lines (use set wrap! from inside vim to manually toggle this)
  set nowrap

" [global] writebackup       make a backup before overwriting a file
  set wb

" [global] backupdir         list of directories for the backup file and swap file
  if (&term == "win32" || "pcterm" || has("gui_win32"))
    set bdir=$VIM\backup
    set directory=$VIM\backup
  else
    set bdir=$HOME/tmp/.vimbk
    set directory=$HOME/tmp/.vimbk
  endif

" [global] undodir           directory for persistent undo
  if (&term == "win32" || "pcterm" || has("gui_win32"))
    set undodir=$VIM\undo
  else
    set undodir=$HOME/tmp/.vimundo
  endif

" insert space characters whenever the tab key is pressed
    set expandtab

" set number of spaces that <Tab> uses while editing
    set tabstop=4

" set number of space characters inserted for indentation
    set shiftwidth=4

" set number of space characters deleted for deindentation
    set softtabstop=4

" highlight all searches (hlsearch/nohlsearch)
    set hlsearch 

" Clear search highlighting (mnemonic: clear search)
nnoremap <Leader>cs :nohlsearch<CR>

"  use space as leader key
:let mapleader = " "

" Print Options "
if !has('nvim')
    set popt=paper:letter
endif

" Mouse support in alacritty
set mouse=a

" Make mouse work also on very wide monitors
if !(has('nvim'))
    if has("mouse_sgr")
        set ttymouse=sgr
    else
        set ttymouse=xterm2
    end
endif

" Bash-like autocompletion when opening a file via :e
" set wildmode=longest:full,full
set wildmode=longest,list,full
set wildmenu

" set gui font
    " set guifont=Lucida_Console:h9:cANSI
"     set guifont=Bitstream\ Vera\ Sans\ Mono\ 9
     set guifont=Inconsolata
autocmd BufRead *.py set smartindent cinwords=if,elif,else,for,while,try,except,finally,def,class
autocmd BufRead *.ipy set smartindent cinwords=if,elif,else,for,while,try,except,finally,def,class

"----------------------------------------------------------------------------------------------------------------------"
" Appearance
"----------------------------------------------------------------------------------------------------------------------"
"
" Force the underlying terminal to use 256 colors
if has("gui_running")
    set t_Co=256
endif

" set color scheme
" Colorscheme is set in init.lua (after Lazy loads plugins)

" Highlight trailing whitespace with a subtle dark grey background.
" Uses match instead of set list so tabs aren't affected.
" The \%#\@<! avoids highlighting while typing at end of line.
" Applied via autocmd so it persists across buffer/window switches
" (match is window-local and gets cleared otherwise).
highlight TrailingWhitespace guibg=#444444 ctermbg=238
let g:trailing_ws_enabled = 1

function! ApplyTrailingWhitespace()
    " Only apply to normal file buffers (skip plugin UIs, popups, terminals)
    if g:trailing_ws_enabled && &buftype ==# ''
        match TrailingWhitespace /\s\+\%#\@<!$/
    else
        match none
    endif
endfunction

augroup TrailingWS
    autocmd!
    autocmd BufWinEnter,WinEnter * call ApplyTrailingWhitespace()
    autocmd ColorScheme * highlight TrailingWhitespace guibg=#444444 ctermbg=238 | call ApplyTrailingWhitespace()
augroup END

" Apply immediately for the first window
call ApplyTrailingWhitespace()

"----------------------------------------------------------------------------------------------------------------------"
" Custom Functions
"----------------------------------------------------------------------------------------------------------------------"

" Toggle trailing whitespace highlighting on/off
function! ToggleTrailingWhitespace()
    if g:trailing_ws_enabled
        " Clear match in all windows
        windo match none
        let g:trailing_ws_enabled = 0
        lua vim.notify("Trailing whitespace highlight OFF", vim.log.levels.INFO)
    else
        " Apply match in all windows
        windo match TrailingWhitespace /\s\+\%#\@<!$/
        let g:trailing_ws_enabled = 1
        lua vim.notify("Trailing whitespace highlight ON", vim.log.levels.INFO)
    endif
endfunction

" Print current buffer to file, according to current color scheme "
function! Print_old()
    hardcopy > /tmp/vim_tmp_for_print.ps
    "exec system("lpr -P sv-prn-4520c-01 -o portrait -o Finisher=Staple1 -o Pedestal=Drawer2 -o PageSize=Letter -o PageRegion=Letter -o InputSlot=Auto -o Duplex=DuplexNoTumble -o Collate=True -o OutputTray=Auto -o HolePunch=Off -o Stapling=Off -o PrintMode=Normal -o DeptCode=False -o TonerSave=False -o BlankPage=False -o DCDigit1=0 -o DCDigit2=0 -o DCDigit3=0 -o DCDigit4=0 -o DCDigit5=0 -o DINDigit1=0 -o DINDigit2=0 -o DINDigit3=0 -o DINDigit4=0 -o DINDigit5=0 -o BookletPaperSize=None -o BookletPageLayout=True -o BookletCenterMargin=Off -o BookletOuterMargin=Off -o ColorType=Color -o Halftone=Auto -o DistinguishThinLines=False -o ImageType=General -o BlackOverPrint=False -o PureBlackGray=Off -o ColorBalanceCyan=0 -o ColorBalanceMagenta=0 -o ColorBalanceYellow=0 -o ColorBalanceBlack=0 -o ContrastTOS=0 -o SharpnessTOS=0 -o BrightnessTOS=0 -o SaturationTOS=0  /tmp/vim_tmp_for_print.ps")
    exec system("lpr -P sv-prn-4520c-01 -o landscape -o Finisher=Staple1 -o Pedestal=Drawer2 -o PageSize=Letter -o PageRegion=Letter -o InputSlot=Auto -o Duplex=DuplexNoTumble -o Collate=True -o OutputTray=Auto -o HolePunch=Off -o Stapling=Off -o PrintMode=Normal -o DeptCode=False -o TonerSave=False -o BlankPage=False -o DCDigit1=0 -o DCDigit2=0 -o DCDigit3=0 -o DCDigit4=0 -o DCDigit5=0 -o DINDigit1=0 -o DINDigit2=0 -o DINDigit3=0 -o DINDigit4=0 -o DINDigit5=0 -o BookletPaperSize=None -o BookletPageLayout=True -o BookletCenterMargin=Off -o BookletOuterMargin=Off -o ColorType=Color -o Halftone=Auto -o DistinguishThinLines=False -o ImageType=General -o BlackOverPrint=False -o PureBlackGray=Off -o ColorBalanceCyan=0 -o ColorBalanceMagenta=0 -o ColorBalanceYellow=0 -o ColorBalanceBlack=0 -o ContrastTOS=0 -o SharpnessTOS=0 -o BrightnessTOS=0 -o SaturationTOS=0  /tmp/vim_tmp_for_print.ps")
endfunction

" Print current buffer to file, according to current color scheme "
function! Print(orientation, ...)
    let usage = "Usage: :call Print(orientation [start_line, end_line])\n\n"
    let l:usage +=  "Example: Print(landscape)\n"

    " Check orientation (mandatory argument)
    if a:orientation == "landscape"
        let is_portrait = "n"
    elseif a:orientation == "portrait"
        let is_portrait = "y"
    else
        echoerr l:usage
        return
    endif

    " Check optional range arguments
    if a:0 != 2 && a:0 != 0
        echoerr l:usage
        return
    endif

    " Define range no matter what was the input
    if a:0 == 0
        let beg = 1
        let end = '$'
    else
        echom "here"
        let beg = a:1
        let end = a:2
    endif

    " Set printing options according to inputs
    execute "set printoptions=paper:letter,portrait:" . l:is_portrait
    " Save current colorscheme and switch to colors suitable for priting
    let color_saved = g:colors_name
    colo shine
    " Create postscript file
    execute beg . "," . end . "hardcopy > /tmp/vim_tmp_for_print.ps"
    " Restore original colorscheme
    execute "colorscheme " . l:color_saved
    " Print ps to file, in color. Note that there is no printoption to force
    " color and MoSys default is grayscale, so we do need the extra step
     exec system("lpr -P hp-m477-copy -o ColorType=Color /tmp/vim_tmp_for_print.ps")

endfunction


function! SavePs(orientation)
    set printoptions=paper:letter,orientation:a:orientation
    hardcopy > /tmp/vim_tmp_for_print.ps
endfunction

command! -complete=shellcmd -nargs=+ Shell call s:RunShellCommand(<q-args>)
function! s:RunShellCommand(cmdline)
  echo a:cmdline
  let expanded_cmdline = a:cmdline
  for part in split(a:cmdline, ' ')
     if part[0] =~ '\v[%#<]'
        let expanded_part = fnameescape(expand(part))
        let expanded_cmdline = substitute(expanded_cmdline, part, expanded_part, '')
     endif
  endfor
  botright new
  setlocal buftype=nofile bufhidden=wipe nobuflisted noswapfile nowrap
  call setline(1, 'You entered:    ' . a:cmdline)
  call setline(2, 'Expanded Form:  ' .expanded_cmdline)
  call setline(3,substitute(getline(2),'.','=','g'))
  execute '$read !'. expanded_cmdline
  setlocal nomodifiable
  1
endfunction


" --------------------------------------------- "
" Zoom / Restore pane                           "
" --------------------------------------------- "
function! s:ZoomToggle() abort
    if exists('t:zoomed') && t:zoomed
        execute t:zoom_winrestcmd
        let t:zoomed = 0
    else
        let t:zoom_winrestcmd = winrestcmd()
        resize
        vertical resize
        let t:zoomed = 1
    endif
endfunction
command! ZoomToggle call s:ZoomToggle()


" --------------------------------------------- "
" Toggle Location list opened/closed            "
" --------------------------------------------- "
function! LocListToggle() abort
    if exists('t:loclist_visible') && t:loclist_visible
        lclose
        let t:loclist_visible = 0
    else
        lopen
        let t:loclist_visible = 1
    endif
endfunction
command! LocToggle call LocListToggle()

" --------------------------------------------- "
" Set indentation to the given number of spaces "
" --------------------------------------------- "
function! s:SetIndent(num_spaces) abort
    " Convert string to number
    let ns = str2nr(a:num_spaces)

    " let &var is the same as setting an option called var
    " let &tabstop=8  ===> set tabstop=8
    " Using set in the function wouldn't work b/c of type issues
    let &tabstop = ns
    let &shiftwidth = ns
    let &softtabstop = ns

    " The . concatenates strings. Echom evaluates the entire thing
    " before printing to stdout.
    echom "Indentation was set to " . a:num_spaces
endfunction
command! -nargs=1 SetIndent call s:SetIndent(<f-args>)


" Select a jump in the jumplist 
function! GotoJump()
  jumps
  let j = input("Please select your jump: ")
  if j != ''
    let pattern = '\v\c^\+'
    if j =~ pattern
      let j = substitute(j, pattern, '', 'g')
      execute "normal " . j . "\<c-i>"
    else
      execute "normal " . j . "\<c-o>"
    endif
  endif
endfunction
nmap <Leader>ji :call GotoJump()<CR>

"----------------------------------------------------------------------------------------------------------------------"
" Mappings
"----------------------------------------------------------------------------------------------------------------------"

" CTRL-Z is Undo; not in cmdline though
noremap <C-Z> u
inoremap <C-Z> <C-O>u

" CTRL-Y is Redo (although not repeat); not in cmdline though
noremap <C-Y> <C-R>
inoremap <C-Y> <C-O><C-R>

" map for quick "change to current directory"
map ,cd :cd %:p:h<CR>

nmap <F12> :call LocListToggle()<ESC>


" TagBar shortcuts
nmap <Leader>tag :TagbarOpen jf<CR>
" The following has been obsoleted by the previous. Remove once muscle memory adapted.
cnoreabbrev tbarf TagbarOpen j

cnoreabbrev tbart TagbarToggle

" Zoom pane shortcut
cnoreabbrev zo ZoomToggle

" Smart pane resize — see lua block below
lua << EOF
-- Smart pane resize: move the nearest border in the arrow direction.
--
-- dir: one of "left", "right", "up", "down" — the direction to move a border.
--
-- winnr() returns the number (1-based index) of the currently focused window.
-- We use it to detect neighbors by jumping and checking if winnr changed.
--
-- Key insight: `vertical resize +/-5` always moves the RIGHT border for
-- non-rightmost windows, but the LEFT border for the rightmost window.
-- Same for `resize` with top/bottom borders. So when the current pane is
-- at the far edge (rightmost for h/l, bottommost for j/k), the resize
-- sign must be inverted to keep the "move border in arrow direction" behavior.
--
-- Examples (3 vertical panes: A | B | C):
--   B + Alt+h: move B's right border left  → vertical resize -5
--   B + Alt+l: move B's right border right → vertical resize +5
--   C + Alt+h: move C's left border left   → vertical resize +5 (inverted)
--   C + Alt+l: move C's left border right  → vertical resize -5 (inverted)

local function smart_resize(dir)
  local cur = vim.fn.winnr()
  local wincmds = { left = "h", right = "l", up = "k", down = "j" }

  -- Check for neighbors in both directions
  vim.cmd("wincmd " .. wincmds[dir])
  local has_dir = vim.fn.winnr() ~= cur
  if has_dir then vim.cmd(cur .. "wincmd w") end

  local opposite_dir = ({ left = "right", right = "left", up = "down", down = "up" })[dir]
  vim.cmd("wincmd " .. wincmds[opposite_dir])
  local has_opp = vim.fn.winnr() ~= cur
  if has_opp then vim.cmd(cur .. "wincmd w") end

  if not has_dir and not has_opp then
    vim.notify("Can't resize in this direction")
    return
  end

  -- Base sign: left/up = shrink (-), right/down = grow (+)
  local sign = (dir == "left" or dir == "up") and -1 or 1

  -- vim's resize always moves the RIGHT border (or BOTTOM for vertical).
  -- Exception: the rightmost (or bottommost) window, where it moves the
  -- LEFT (or TOP) border instead — effectively inverting the direction.
  -- Detect this by checking for a neighbor in the "positive" direction
  -- (right for horizontal, down for vertical).
  local positive_dir = (dir == "left" or dir == "right") and "right" or "down"
  local has_positive
  if positive_dir == dir then
    has_positive = has_dir
  else
    has_positive = has_opp
  end
  if not has_positive then sign = -sign end

  local is_vertical = (dir == "left" or dir == "right")
  local cmd = is_vertical
    and ("vertical resize " .. (sign > 0 and "+5" or "-5"))
    or  ("resize " .. (sign > 0 and "+5" or "-5"))
  vim.cmd(cmd)
end

-- Bind Alt+Arrow and Alt+hjkl keys to smart resize
vim.keymap.set("", "<A-Left>",  function() smart_resize("left") end)
vim.keymap.set("", "<A-Right>", function() smart_resize("right") end)
vim.keymap.set("", "<A-Up>",    function() smart_resize("up") end)
vim.keymap.set("", "<A-Down>",  function() smart_resize("down") end)
vim.keymap.set("", "<A-h>",     function() smart_resize("left") end)
vim.keymap.set("", "<A-l>",     function() smart_resize("right") end)
vim.keymap.set("", "<A-k>",     function() smart_resize("up") end)
vim.keymap.set("", "<A-j>",     function() smart_resize("down") end)
EOF
"

" Switch focus to the leftmost window.
" This is useful to switch focuse to either Nnn, NerdTree or other treeviewers
" when they are opened as the leftmost panes. To switch focus to TagBar see
" the dedicated abbrev
nmap <Leader>l 1<C-w><C-w>


"----------------------------------------------------------------------------------------------------------------------"
" Autocommands
"----------------------------------------------------------------------------------------------------------------------"

" In text files, always limit the width of text to 78 characters.
"autocmd BufRead *.txt set textwidth=78

au BufRead,BufNewFile *.stil    setfiletype stil
au BufRead,BufNewFile *.tcl    setfiletype tcl
au BufRead,BufNewFile *.pasm   setfiletype pasm
au BufRead,BufNewFile *.pasm   set syntax=pasm
au BufRead,BufNewFile *.acl    setfiletype acl
au BufRead,BufNewFile *.acl   set syntax=acl
au BufRead,BufNewFile *.cam    setfiletype cam
au BufRead,BufNewFile *.cam   set syntax=cam
au BufRead,BufNewFile *.uws    setfiletype uws
au BufRead,BufNewFile *.uws   set syntax=uws
"
" au BufRead,BufNewFile *.c      set tabstop=2
" au BufRead,BufNewFile *.c      set shiftwidth=2
" au BufRead,BufNewFile *.cpp      set tabstop=4
" au BufRead,BufNewFile *.cpp      set shiftwidth=4
"
au BufRead,BufNewFile *.lua      setlocal shiftwidth=2 tabstop=2 softtabstop=2 expandtab
au BufRead,BufNewFile *.uws      setlocal shiftwidth=2 tabstop=2 softtabstop=2 expandtab
au BufRead,BufNewFile *.h        setlocal shiftwidth=4 tabstop=4 softtabstop=4 expandtab
au BufRead,BufNewFile *.c        setlocal shiftwidth=4 tabstop=4 softtabstop=4 expandtab
au BufRead,BufNewFile *.cpp      setlocal shiftwidth=4 tabstop=4 softtabstop=4 expandtab
au BufRead,BufNewFile *.py       setlocal shiftwidth=4 tabstop=4 softtabstop=4 expandtab
au BufRead,BufNewFile *.pasm     setlocal shiftwidth=4 tabstop=4 softtabstop=4 expandtab
au BufRead,BufNewFile *.uasm     setlocal shiftwidth=4 tabstop=4 softtabstop=4 expandtab

" Force a syntax highlighting sync when you enter a buffer
" Normally syntax is cached so this is useful when developing syntax files
autocmd BufEnter * :syntax sync fromstart


" Change shape of cursor in different modes in vim -- commented out b/c it lows things down if gconftool-2 is not installed
" au InsertEnter * silent execute "!gconftool-2 --type string --set /apps/gnome-terminal/profiles/Default/cursor_shape ibeam"
" au InsertLeave * silent execute "!gconftool-2 --type string --set /apps/gnome-terminal/profiles/Default/cursor_shape block"
" au VimLeave * silent execute "!gconftool-2 --type string --set /apps/gnome-terminal/profiles/Default/cursor_shape ibeam"

"----------------------------------------------------------------------------------------------------------------------"
" Plugins
"----------------------------------------------------------------------------------------------------------------------"

" TagBar
" rely on ctags being in PATH
let tagbar_ctags_bin='ctags'
let g:tagbar_position = 'left'
" Write rust tags upone saving file
autocmd BufWritePost *.rs :silent! exec "!rusty-tags vi --quiet --start-dir=" . expand('%:p:h') . "&" | redraw!




" Vimspector
" ------------
if !has('nvim')
    let g:vimspector_enable_mappings = 'HUMAN'
    packadd! vimspector
    nnoremap <Leader>dl :call vimspector#Launch()<CR>
    nnoremap <Leader>dq :call vimspector#Reset()<CR>
    nnoremap <Leader>dc :call vimspector#Continue()<CR>

    nnoremap <Leader>db :call vimspector#ToggleBreakpoint()<CR>
    nnoremap <Leader>dB :call vimspector#ClearBreakpoints()<CR>

    nmap <Leader>dr <Plug>VimspectorRestart
    nmap <Leader>dso <Plug>VimspectorStepOut
    nmap <Leader>ds <Plug>VimspectorStepInto
    nmap <Leader>dn <Plug>VimspectorStepOver
endif

" Rooter
" ------------
let g:rooter_patterns = ['.git']
let g:rooter_manual_only = 1
nnoremap <silent> <Leader>R :Rooter<CR>

" Gitsigns (replaced vim-gitgutter, see lua/plugins/nav/gitsigns.lua)
" Refresh every 500ms (default=4s, shared with swap file update)
set updatetime=500

" FZF
" ---------
let $FZF_DEFAULT_COMMAND="rg --files --hidden -g '!.git'"
nnoremap <silent> <Leader>b :Buffers<CR>
" fuzzy find files
nnoremap <silent> <Leader>ff :Files<CR>
" fuzzy find files matching word under cursor
nnoremap <silent> <Leader>fw :call fzf#vim#files('', {'options': ['--query', expand('<cword>')]})<CR>
nnoremap <silent> <Leader>/ :BLines<CR>
nnoremap <silent> <Leader>' :Marks<CR>
nnoremap <silent> <Leader>gC :Commits<CR>
nnoremap <silent> <Leader>H :Helptags<CR>
nnoremap <silent> <Leader>hh :History<CR>
nnoremap <silent> <Leader>h: :History:<CR>
nnoremap <silent> <Leader>h/ :History/<CR> 
" Use ripgrep to search in files (find all)
nnoremap <silent> <Leader>fa :Rg<CR>
" ... but exclude file names from search results
command! -bang -nargs=* Rg call fzf#vim#grep("rg --column --line-number --no-heading --color=always --smart-case --ignore-file=tags ".shellescape(<q-args>), 1, {'options': '--delimiter : --nth 4..'}, <bang>0)

if has('win32') || has ('win64')
    let $VIMHOME = $VIM."/vimfiles"
else
    let $VIMHOME = $HOME."/.vim"
endif
source $VIMHOME/jumplist_fzf.vim


" Zoxide
" ------
let g:zoxide_prefix = 'j'

" NNN
" ------
map <Leader>nnn :NnnExplorer<CR>

" CtrlSF
" ------
" prompt
nmap <Leader>sfp <Plug>CtrlSFPrompt 
" toggle open/close  
nmap <Leader>sft :CtrlSFToggle<CR>
" search current visual selection
vmap <Leader>sfc <Plug>CtrlSFVwordPath
" search word under cursor
nmap <Leader>sfc <Plug>CtrlSFCwordPath
" focus the CtrlSF results pane
nmap <Leader>sff :CtrlSFFocus<CR>


" 
" EasyGrep
" ---------
"  This unfortunately will make fzf look inside the files when using <leader-f>
"  let g:EasyGrepCommand='rg'

" QuickUI
" ---------
command! TmuxPaste put =system('tmux show-buffer')

let g:quickui_border_style = 4
let g:quickui_color_scheme = 'papercol_dark'

call quickui#menu#reset()

call quickui#menu#install('&Navigate', [
			\ [ "&Files\t\\ff", 'Files', 'FZF find files' ],
			\ [ "Files by &Word\t\\fw", 'call fzf#vim#files("", {"options": ["--query", expand("<cword>")]})', 'FZF find file by word under cursor' ],
			\ [ "&Buffers\t\\b", 'Buffers', 'Switch between open buffers' ],
			\ [ "Buffer &Lines\t\\/", 'BLines', 'Search lines in current buffer' ],
			\ [ "&Marks\t\\''", 'Marks', 'Jump to marks' ],
			\ [ "--", ],
			\ [ "&Outline Toggle\t\\oo", 'Outline', 'Toggle symbol outline sidebar' ],
			\ [ "Outline &Focus\t\\of", 'OutlineFocusOutline', 'Focus the outline window' ],
			\ [ "&Tagbar\t\\tag", 'TagbarOpen jf', 'Open tagbar and jump to it' ],
			\ [ "--", ],
			\ [ "&NNN Explorer\t\\nnn", 'NnnExplorer', 'Toggle nnn file explorer' ],
			\ [ "NNN &Sync to File\t\\ns", 'exec "normal \\<Leader>ns"', 'Navigate nnn to current file dir' ],
			\ [ "NNN &Focus\t\\nf", 'exec "normal \\<Leader>nf"', 'Focus nnn pane (open if closed)' ],
			\ ])

call quickui#menu#install('&LSP', [
			\ [ "Goto &Definition\tgd", 'Telescope lsp_definitions', 'Jump to symbol definition' ],
			\ [ "Goto D&eclaration\tgD", 'lua vim.lsp.buf.declaration()', 'Jump to symbol declaration' ],
			\ [ "Goto &Implementation\tgi", 'Telescope lsp_implementations', 'Jump to implementation' ],
			\ [ "Goto &References\tgR", 'Telescope lsp_references', 'Show all references' ],
			\ [ "Goto &Type Definition\tgt", 'Telescope lsp_type_definitions', 'Jump to type definition' ],
			\ [ "--", ],
			\ [ "&Hover Documentation\t\\k", 'lua vim.lsp.buf.hover()', 'Show hover docs for symbol' ],
			\ [ "Code &Actions\t\\ca", 'lua vim.lsp.buf.code_action()', 'Available code actions' ],
			\ [ "&Rename Symbol\t\\rn", 'lua vim.lsp.buf.rename()', 'Rename symbol across project' ],
			\ [ "--", ],
			\ [ "&Buffer Diagnostics\t\\D", 'Telescope diagnostics bufnr=0', 'Show diagnostics for current buffer' ],
			\ [ "&Show Line Diagnostics\t\\ds", 'lua vim.diagnostic.open_float()', 'Show diagnostics for current line' ],
			\ [ "&Next Diagnostic\t\\dn", 'lua vim.diagnostic.goto_next()', 'Jump to next diagnostic' ],
			\ [ "&Prev Diagnostic\t\\dp", 'lua vim.diagnostic.goto_prev()', 'Jump to previous diagnostic' ],
			\ [ "&Toggle Diagnostics\t\\dt", 'exec "normal \\<Leader>dt"', 'Toggle diagnostics on/off' ],
			\ [ "--", ],
			\ [ "Restart L&SP\t\\rs", 'LspRestart', 'Restart LSP server' ],
			\ ])

call quickui#menu#install('&Search', [
			\ [ "CtrlSF &Prompt\t\\sfp", 'call feedkeys("\<Plug>CtrlSFPrompt")', 'Open CtrlSF search prompt' ],
			\ [ "CtrlSF &Word Under Cursor\t\\sfc", 'call feedkeys("\<Plug>CtrlSFCwordPath")', 'Search word under cursor with CtrlSF' ],
			\ [ "CtrlSF &Toggle Results\t\\sft", 'CtrlSFToggle', 'Toggle CtrlSF results window' ],
			\ [ "--", ],
			\ [ "&Ripgrep\t:Rg", 'Rg', 'Search with ripgrep' ],
			\ [ "&Commits\t\\gC", 'Commits', 'Search git commits' ],
			\ ])

call quickui#menu#install('&Git', [
			\ [ "&Next Hunk\t\\hn", 'Gitsigns next_hunk', 'Jump to next changed hunk' ],
			\ [ "&Prev Hunk\t\\hp", 'Gitsigns prev_hunk', 'Jump to previous changed hunk' ],
			\ [ "Pre&view Hunk\t\\hv", 'Gitsigns preview_hunk', 'Preview hunk changes' ],
			\ [ "--", ],
			\ [ "&Undo Hunk", 'Gitsigns undo_stage_hunk', 'Undo staged hunk' ],
			\ [ "&Stage Hunk", 'Gitsigns stage_hunk', 'Stage hunk for commit' ],
			\ [ "&Reset Hunk", 'Gitsigns reset_hunk', 'Revert hunk to git version' ],
			\ [ "Se&lect Hunk", 'Gitsigns select_hunk', 'Select hunk as text object' ],
			\ [ "--", ],
			\ [ "Toggle Line &Blame", 'Gitsigns toggle_current_line_blame', 'Show/hide blame at end of line' ],
			\ [ "&Diff This\t\\hd", 'Gitsigns diffthis', 'Diff current file against index' ],
			\ ])

call quickui#menu#install('&Fold', [
			\ [ "Close &All\tzM", 'lua require("ufo").closeAllFolds()', 'Fold everything' ],
			\ [ "Open A&ll\tzR", 'lua require("ufo").openAllFolds()', 'Unfold everything' ],
			\ [ "&Toggle Under Cursor\tza", 'normal! za', 'Toggle fold at cursor' ],
			\ [ "&Peek Fold\tzp", 'lua require("ufo").peekFoldedLinesUnderCursor()', 'Preview folded content' ],
			\ [ "--", ],
			\ [ "Open &One More Level\tzr", 'normal! zr', 'Open one more fold level globally' ],
			\ [ "Close One &More Level\tzm", 'normal! zm', 'Close one more fold level globally' ],
			\ ])

call quickui#menu#install('&AI', [
			\ [ "Avante &Ask\t\\aaa", 'AvanteAsk', 'Open Avante chat sidebar' ],
			\ [ "Avante &Edit Selection\t\\aae", 'AvanteEdit', 'Edit selected code with AI' ],
			\ [ "Avante &Toggle Sidebar\t\\aat", 'AvanteToggle', 'Toggle Avante sidebar visibility' ],
			\ [ "--", ],
			\ [ "Claude &Toggle\t\\act", 'ClaudeCode', 'Toggle Claude Code terminal' ],
			\ [ "Claude &Send Selection\t\\acs", 'ClaudeCodeSend', 'Send selection to Claude' ],
			\ [ "Claude A&dd File\t\\acd", 'ClaudeCodeAdd', 'Add file to Claude context' ],
			\ ])

call quickui#menu#install('&Misc', [
			\ [ "Paste from &Tmux Buffer", 'TmuxPaste', 'Insert tmux paste buffer below cursor' ],
			\ [ "--", ],
			\ [ "Toggle &Trailing Whitespace", 'call ToggleTrailingWhitespace()', 'Show/hide trailing whitespace highlight' ],
			\ [ "Toggle Cursor &Column", 'set cursorcolumn!', 'Show/hide vertical cursor column guide' ],
			\ [ "--", ],
			\ [ "Session &Save\t\\sss", 'call feedkeys("\\sss")', 'Save named session' ],
			\ [ "Session &Load\t\\ssl", 'call feedkeys("\\ssl")', 'Load saved session' ],
			\ [ "Session &Delete\t\\ssd", 'call feedkeys("\\ssd")', 'Delete saved session' ],
			\ ])

let g:context_menu_k = [
			\ [ "&Peek Definition\tgd", 'Telescope lsp_definitions', 'Jump to definition' ],
			\ [ "Show &References\tgR", 'Telescope lsp_references', 'Show all references' ],
			\ [ "&Hover Doc\t\\k", 'lua vim.lsp.buf.hover()', 'Show documentation' ],
			\ [ "--", ],
			\ [ "&Search in Project\t\\sfc", 'call feedkeys("\<Plug>CtrlSFCwordPath")', 'CtrlSF search word under cursor' ],
			\ [ "&Grep in Project\t:Rg", 'exec "Rg " . expand("<cword>")', 'Ripgrep word under cursor' ],
			\ [ "--", ],
			\ [ "Rename S&ymbol\t\\rn", 'lua vim.lsp.buf.rename()', 'Rename symbol' ],
			\ [ "Code &Actions\t\\ca", 'lua vim.lsp.buf.code_action()', 'Code actions' ],
			\ [ "--", ],
			\ [ 'P&ython Doc', 'call quickui#tools#python_help("")', 'python' ],
			\ ]


nnoremap <silent><space><space> :call quickui#menu#open()<cr>

nnoremap <silent>K :call quickui#tools#clever_context('k', g:context_menu_k, {})<cr>
